# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler -v '2.3.26'

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run tests
        run: bundle exec rspec
